samples/WebApplicationSample/Controllers/HomeController.cs
using System.Diagnostics;
using System.Drawing;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using QRCoder;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// 前言
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 打赏
        /// </summary>
        /// <returns></returns>
        public IActionResult Gratuity()
        {
            return View();
        }

        /// <summary>
        /// 生成二维码SVG
        /// </summary>
        /// <param name="data"></param>
        /// <param name="size"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QrCode(string data, int size = 168)
        {
            using (var qrGenerator = new QRCodeGenerator())
            using (var qrCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.L))
            using (var svgQrCode = new SvgQRCode(qrCodeData))
            {
                var svgText = svgQrCode.GetGraphic(new Size(size, size));
                return File(Encoding.UTF8.GetBytes(svgText), "text/xml");
            }
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

samples/WebApplicationSample/Controllers/QPayController.cs
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.QPay;
using Essensoft.AspNetCore.Payment.QPay.Request;
using Essensoft.AspNetCore.Payment.Security;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class QPayController : Controller
    {
        private readonly IQPayClient _client;
        private readonly IOptions<QPayOptions> _optionsAccessor;

        public QPayController(IQPayClient client, IOptions<QPayOptions> optionsAccessor)
        {
            _client = client;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// QQ钱包指引页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 付款码支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult MicroPay()
        {
            return View();
        }

        /// <summary>
        /// 付款码支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> MicroPay(QPayMicroPayViewModel viewModel)
        {
            var request = new QPayMicroPayRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
                Body = viewModel.Body,
                FeeType = viewModel.FeeType,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                DeviceInfo = viewModel.DeviceInfo,
                AuthCode = viewModel.AuthCode,
                TradeType = viewModel.TradeType,
                NotifyUrl = viewModel.NotifyUrl
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QrCodePay()
        {
            return View();
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> QrCodePay(QPayUnifiedOrderViewModel viewModel)
        {
            var request = new QPayUnifiedOrderRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
                Body = viewModel.Body,
                FeeType = viewModel.FeeType,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                TradeType = viewModel.TradeType,
                NotifyUrl = viewModel.NotifyUrl
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["qrcode"] = response.CodeUrl;
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 公众号支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult PubPay()
        {
            return View();
        }

        /// <summary>
        /// 公众号支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PubPay(QPayUnifiedOrderViewModel viewModel)
        {
            var request = new QPayUnifiedOrderRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
                Body = viewModel.Body,
                FeeType = viewModel.FeeType,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                TradeType = viewModel.TradeType,
                NotifyUrl = viewModel.NotifyUrl
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AppPay()
        {
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AppPay(QPayUnifiedOrderViewModel viewModel)
        {
            var request = new QPayUnifiedOrderRequest
            {
                OutTradeNo = viewModel.OutTradeNo,
                Body = viewModel.Body,
                FeeType = viewModel.FeeType,
                TotalFee = viewModel.TotalFee,
                SpBillCreateIp = viewModel.SpBillCreateIp,
                TradeType = viewModel.TradeType,
                NotifyUrl = viewModel.NotifyUrl
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 订单查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult OrderQuery()
        {
            return View();
        }

        /// <summary>
        /// 订单查询
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> OrderQuery(QPayOrderQueryViewModel viewModel)
        {
            var request = new QPayOrderQueryRequest
            {
                TransactionId = viewModel.TransactionId,
                OutTradeNo = viewModel.OutTradeNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 撤销订单
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Reverse()
        {
            return View();
        }

        /// <summary>
        /// 撤销订单
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Reverse(QPayReverseViewModel viewModel)
        {
            var request = new QPayReverseRequest
            {
                OutTradeNo = viewModel.OutTradeNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 关闭订单
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CloseOrder()
        {
            return View();
        }

        /// <summary>
        /// 关闭订单
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> CloseOrder(QPayCloseOrderViewModel viewModel)
        {
            var request = new QPayCloseOrderRequest
            {
                OutTradeNo = viewModel.OutTradeNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 申请退款
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Refund()
        {
            return View();
        }

        /// <summary>
        /// 申请退款
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Refund(QPayRefundViewModel viewModel)
        {
            var request = new QPayRefundRequest
            {
                OutRefundNo = viewModel.OutRefundNo,
                TransactionId = viewModel.TransactionId,
                OutTradeNo = viewModel.OutTradeNo,
                RefundFee = viewModel.RefundFee,
                OpUserId = viewModel.OpUserId,
                OpUserPasswd = MD5.Compute(viewModel.OpUserPasswd).ToUpper(),
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult RefundQuery()
        {
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RefundQuery(QPayRefundQueryViewModel viewModel)
        {
            var request = new QPayRefundQueryRequest
            {
                RefundId = viewModel.RefundId,
                OutRefundNo = viewModel.OutRefundNo,
                TransactionId = viewModel.TransactionId,
                OutTradeNo = viewModel.OutTradeNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 对账单下载
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult StatementDown()
        {
            return View();
        }

        /// <summary>
        /// 对账单下载
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]

samples/WebApplicationSample/Controllers/UnionPayController.cs
using System.Text;
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.UnionPay;
using Essensoft.AspNetCore.Payment.UnionPay.Notify;
using Essensoft.AspNetCore.Payment.UnionPay.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class UnionPayController : Controller
    {
        private readonly IUnionPayClient _client;
        private readonly IUnionPayNotifyClient _notifyClient;
        private readonly IOptions<UnionPayOptions> _optionsAccessor;

        public UnionPayController(IUnionPayClient client, IUnionPayNotifyClient notifyClient, IOptions<UnionPayOptions> optionsAccessor)
        {
            _client = client;
            _notifyClient = notifyClient;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 银联支付指引页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 跳转网关页面支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GatewayPayFrontConsume()
        {
            return View();
        }

        /// <summary>
        /// 跳转网关页面支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> GatewayPayFrontConsume(GatewayPayFrontConsumeFrontConsumeViewModel viewModel)
        {
            var request = new UnionPayGatewayPayFrontConsumeRequest
            {
                TxnType = "01",
                TxnSubType = "01",
                BizType = "000201",
                ChannelType = "07",
                OrderId = viewModel.OrderId,
                TxnTime = viewModel.TxnTime,
                TxnAmt = viewModel.TxnAmt,
                CurrencyCode = viewModel.CurrencyCode,
                PayTimeOut = viewModel.PayTimeOut,
                FrontUrl = viewModel.FrontUrl,
                BackUrl = viewModel.BackUrl
            };
            var response = await _client.PageExecuteAsync(request, _optionsAccessor.Value);
            return Content(response.Body, "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// 网关页面支付 - 同步跳转
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> GatewayPayFrontConsumeReturn()
        {
            try
            {
                var notify = await _notifyClient.ExecuteAsync<UnionPayGatewayPayFrontConsumeReturn>(Request, _optionsAccessor.Value);
                ViewData["response"] = "支付成功";
                return View();
            }
            catch
            {
                ViewData["response"] = "出现错误";
                return View();
            }
        }
    }
}

samples/WebApplicationSample/Views/Home/Gratuity.cshtml
@{
    ViewData["Title"] = "打赏";
}
<div align="center">
    <img src="~/images/qrcode.png">
    <hr />
    <p>感谢你对本项目的支持!!!</p>
</div>

samples/WebApplicationSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "前言";
}
<p>
    Payment 基于 .NET Core / ASP.NET Core 开发，支持多商户的跨平台支付SDK集。 简化了API调用及相关通知的处理流程。
</p>
<p class="text-danger">
    注: 本Demo仅作为测试用途，基本涵盖了常用的API。用作实际业务时，请务必配合相关API文档及说明处理。
</p>
<br />
<h5>NuGet 程序包:</h5>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Package</th>
            <th scope="col">NuGet</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td><a asp-controller="Alipay" asp-action="Index">支付宝</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.Alipay" target="_blank">Essensoft.AspNetCore.Payment.Alipay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.Alipay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.Alipay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td><a asp-controller="WeChatPay" asp-action="Index">微信支付</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.WeChatPay" target="_blank">Essensoft.AspNetCore.Payment.WeChatPay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.WeChatPay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.WeChatPay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td><a asp-controller="QPay" asp-action="Index">QQ钱包</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.QPay" target="_blank">Essensoft.AspNetCore.Payment.QPay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.QPay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.QPay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td><a asp-controller="JDPay" asp-action="Index">京东支付</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.JDPay" target="_blank">Essensoft.AspNetCore.Payment.JDPay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.JDPay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.JDPay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.LianLianPay" target="_blank">Essensoft.AspNetCore.Payment.LianLianPay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.LianLianPay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.LianLianPay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td><a asp-controller="UnionPay" asp-action="Index">银联支付</a></td>
            <td><a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.UnionPay" target="_blank">Essensoft.AspNetCore.Payment.UnionPay</a></td>
            <td>
                <a href="https://www.nuget.org/packages/Essensoft.AspNetCore.Payment.UnionPay" target="_blank">
                    <img src="https://img.shields.io/nuget/v/Essensoft.AspNetCore.Payment.UnionPay.svg?style=flat-square" />
                </a>
            </td>
        </tr>
    </tbody>
</table>