samples/WebApplicationSample/Models/LianLianPayViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationSample.Models
{
    public class LianLianPayWebQuickPayViewModel
    {
        [Required]
        [Display(Name = "no_order")]
        public string NoOrder { get; set; }

        [Required]
        [Display(Name = "dt_order")]
        public string DtOrder { get; set; }

        [Required]
        [Display(Name = "money_order")]
        public string MoneyOrder { get; set; }

        [Required]
        [Display(Name = "name_goods")]
        public string NameGoods { get; set; }

        [Required]
        [Display(Name = "user_id")]
        public string UserId { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Display(Name = "url_return")]
        public string UrlReturn { get; set; }

        [Required]
        [Display(Name = "risk_item")]
        public string RiskItem { get; set; }
    }

    public class LianLianPayH5QuickPayViewModel
    {
        [Required]
        [Display(Name = "no_order")]
        public string NoOrder { get; set; }

        [Required]
        [Display(Name = "dt_order")]
        public string DtOrder { get; set; }

        [Required]
        [Display(Name = "money_order")]
        public string MoneyOrder { get; set; }

        [Required]
        [Display(Name = "name_goods")]
        public string NameGoods { get; set; }

        [Required]
        [Display(Name = "user_id")]
        public string UserId { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Display(Name = "url_return")]
        public string UrlReturn { get; set; }

        [Required]
        [Display(Name = "risk_item")]
        public string RiskItem { get; set; }
    }

    public class LianLianPayOrderQueryViewModel
    {
        [Required]
        [Display(Name = "no_order")]
        public string NoOrder { get; set; }

        [Display(Name = "dt_order")]
        public string DtOrder { get; set; }

        [Display(Name = "oid_paybill")]
        public string OidPayBill { get; set; }
    }

    public class LianLianPayRefundViewModel
    {
        [Required]
        [Display(Name = "no_refund")]
        public string NoRefund { get; set; }

        [Required]
        [Display(Name = "dt_refund")]
        public string DtRefund { get; set; }

        [Required]
        [Display(Name = "money_refund")]
        public string MoneyRefund { get; set; }

        [Display(Name = "no_order")]
        public string NoOrder { get; set; }

        [Display(Name = "dt_order")]
        public string DtOrder { get; set; }

        [Display(Name = "oid_paybill")]
        public string OidPayBill { get; set; }

        [Required]
        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class LianLianPayRefundQueryViewModel
    {
        [Display(Name = "no_refund")]
        public string NoRefund { get; set; }

        [Display(Name = "dt_refund")]
        public string DtRefund { get; set; }

        [Display(Name = "oid_refundno")]
        public string OidRefundNo { get; set; }
    }
}

samples/WebApplicationSample/Controllers/LianLianPayController.cs
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.LianLianPay;
using Essensoft.AspNetCore.Payment.LianLianPay.Notify;
using Essensoft.AspNetCore.Payment.LianLianPay.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class LianLianPayController : Controller
    {
        private readonly ILianLianPayClient _client;
        private readonly ILianLianPayNotifyClient _notifyClient;
        private readonly IOptions<LianLianPayOptions> _optionsAccessor;

        public LianLianPayController(ILianLianPayClient client, ILianLianPayNotifyClient notifyClient, IOptions<LianLianPayOptions> optionsAccessor)
        {
            _client = client;
            _notifyClient = notifyClient;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 连连支付指引页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// WEB快捷支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult WebQuickPay()
        {
            return View();
        }

        /// <summary>
        /// WEB快捷支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> WebQuickPay(LianLianPayWebQuickPayViewModel viewModel)
        {
            var request = new LianLianPayCreateBillRequest
            {
                UserId = viewModel.UserId,
                NoOrder = viewModel.NoOrder,
                DtOrder = viewModel.DtOrder,
                NameGoods = viewModel.NameGoods,
                MoneyOrder = viewModel.MoneyOrder,
                NotifyUrl = viewModel.NotifyUrl,
                UrlReturn = viewModel.UrlReturn,
                RiskItem = viewModel.RiskItem,
                FlagPayProduct = "0",
                FlagChnl = "2"
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            return Redirect(response.GatewayUrl);
        }

        /// <summary>
        /// H5快捷支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult H5QuickPay()
        {
            return View();
        }

        /// <summary>
        /// H5快捷支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> H5QuickPay(LianLianPayH5QuickPayViewModel viewModel)
        {
            var request = new LianLianPayCreateBillRequest
            {
                UserId = viewModel.UserId,
                NoOrder = viewModel.NoOrder,
                DtOrder = viewModel.DtOrder,
                NameGoods = viewModel.NameGoods,
                MoneyOrder = viewModel.MoneyOrder,
                NotifyUrl = viewModel.NotifyUrl,
                UrlReturn = viewModel.UrlReturn,
                RiskItem = viewModel.RiskItem,
                FlagPayProduct = "0",
                FlagChnl = "3"
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            return Redirect(response.GatewayUrl);
        }

        /// <summary>
        /// 订单查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult OrderQuery()
        {
            return View();
        }

        /// <summary>
        /// 订单查询
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> OrderQuery(LianLianPayOrderQueryViewModel viewModel)
        {
            var request = new LianLianPayOrderQueryRequest
            {
                NoOrder = viewModel.NoOrder,
                DtOrder = viewModel.DtOrder,
                OidPayBill = viewModel.OidPayBill
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 退款
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Refund()
        {
            return View();
        }

        /// <summary>
        /// 退款
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Refund(LianLianPayRefundViewModel viewModel)
        {
            var request = new LianLianPayRefundRequest
            {
                NoRefund = viewModel.NoRefund,
                DtRefund = viewModel.DtRefund,
                MoneyRefund = viewModel.MoneyRefund,
                NoOrder = viewModel.NoOrder,
                DtOrder = viewModel.DtOrder,
                OidPaybill = viewModel.OidPayBill,
                NotifyUrl = viewModel.NotifyUrl
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult RefundQuery()
        {
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RefundQuery(LianLianPayRefundQueryViewModel viewModel)
        {
            var request = new LianLianPayRefundQueryRequest
            {
                NoRefund = viewModel.NoRefund,
                DtRefund = viewModel.DtRefund,
                OidRefundNo = viewModel.OidRefundNo
            };
            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 快捷支付 - 同步跳转
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> QuickPayReturn()
        {
            try
            {
                var notify = await _notifyClient.ExecuteAsync<LianLianPayReceiveMoneyReturnResponse>(Request, _optionsAccessor.Value);
                ViewData["response"] = "支付成功";
                return View();
            }
            catch
            {
                ViewData["response"] = "出现错误";
                return View();
            }
        }
    }
}

samples/WebApplicationSample/Views/LianLianPay/H5QuickPay.cshtml
@model LianLianPayH5QuickPayViewModel
@{
    ViewData["Title"] = "H5快捷支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="LianLianPay" asp-action="H5QuickPay" target="_blank">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoOrder"></label>
                <input type="text" class="form-control" asp-for="NoOrder" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="DtOrder"></label>
                <input type="text" class="form-control" asp-for="DtOrder" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="MoneyOrder"></label>
                <input type="text" class="form-control" asp-for="MoneyOrder" value="0.01" />
            </div>
            <div class="form-group">
                <label asp-for="NameGoods"></label>
                <input type="text" class="form-control" asp-for="NameGoods" value="WAP快捷支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="UserId"></label>
                <input type="text" class="form-control" asp-for="UserId" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/lianlianpay/receivemoney" />
            </div>
            <div class="form-group">
                <label asp-for="UrlReturn"></label>
                <input type="text" class="form-control" asp-for="UrlReturn" value="http://*/lianlianpay/quickpayreturn" />
            </div>
            <div class="form-group">
                <label asp-for="RiskItem"></label>
                <input type="text" class="form-control" asp-for="RiskItem" value='{"frms_ware_category":"1999","user_info_full_name":"你好"}' />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/LianLianPay/Index.cshtml
@{
    ViewData["Title"] = "连连支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">首页</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">产品</th>
            <th scope="col">接口</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Web快捷支付</td>
            <td><a href="http://open.lianlianpay.com/#cat=35" target="_blank">https://payment.lianlianpay.com/payment/bankgateway.htm</a></td>
            <td><a asp-controller="LianLianPay" asp-action="WebQuickPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>H5快捷支付</td>
            <td><a href="http://open.lianlianpay.com/#cat=36" target="_blank">https://wap.lianlianpay.com/payment.htm</a></td>
            <td><a asp-controller="LianLianPay" asp-action="H5QuickPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>订单查询</td>
            <td><a href="http://open.lianlianpay.com/#cat=36" target="_blank">https://queryapi.lianlianpay.com/orderquery.htm</a></td>
            <td><a asp-controller="LianLianPay" asp-action="OrderQuery">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>退款</td>
            <td><a href="http://open.lianlianpay.com/#cat=74" target="_blank">https://traderapi.lianlianpay.com/refund.htm</a></td>
            <td><a asp-controller="LianLianPay" asp-action="Refund">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>退款查询</td>
            <td><a href="http://open.lianlianpay.com/#cat=74" target="_blank">https://queryapi.lianlianpay.com/refundquery.htm</a></td>
            <td><a asp-controller="LianLianPay" asp-action="RefundQuery">立即测试</a></td>
        </tr>
    </tbody>
</table>

samples/WebApplicationSample/Views/LianLianPay/OrderQuery.cshtml
@model LianLianPayOrderQueryViewModel
@{
    ViewData["Title"] = "订单查询";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="LianLianPay" asp-action="OrderQuery">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoOrder"></label>
                <input type="text" class="form-control" asp-for="NoOrder" />
            </div>
            <div class="form-group">
                <label asp-for="DtOrder"></label>
                <input type="text" class="form-control" asp-for="DtOrder" />
            </div>
            <div class="form-group">
                <label asp-for="OidPayBill"></label>
                <input type="text" class="form-control" asp-for="OidPayBill" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/LianLianPay/QuickPayCallback.cshtml
@{
    ViewData["Title"] = "快捷支付-同步通知";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        @ViewData["response"]
    </div>
</div>

samples/WebApplicationSample/Views/LianLianPay/Refund.cshtml
@model LianLianPayRefundViewModel
@{
    ViewData["Title"] = "退款";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="LianLianPay" asp-action="Refund">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoRefund"></label>
                <input type="text" class="form-control" asp-for="NoRefund" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="DtRefund"></label>
                <input type="text" class="form-control" asp-for="DtRefund" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="MoneyRefund"></label>
                <input type="text" class="form-control" asp-for="MoneyRefund" value="0.01" />
            </div>
            <div class="form-group">
                <label asp-for="NoOrder"></label>
                <input type="text" class="form-control" asp-for="NoOrder" />
            </div>
            <div class="form-group">
                <label asp-for="DtOrder"></label>
                <input type="text" class="form-control" asp-for="DtOrder" />
            </div>
            <div class="form-group">
                <label asp-for="OidPayBill"></label>
                <input type="text" class="form-control" asp-for="OidPayBill" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/lianlianpay/refund" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/LianLianPay/RefundQuery.cshtml
@model LianLianPayRefundQueryViewModel
@{
    ViewData["Title"] = "退款查询";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="LianLianPay" asp-action="RefundQuery">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoRefund"></label>
                <input type="text" class="form-control" asp-for="NoRefund" />
            </div>
            <div class="form-group">
                <label asp-for="DtRefund"></label>
                <input type="text" class="form-control" asp-for="DtRefund" />
            </div>
            <div class="form-group">
                <label asp-for="OidRefundNo"></label>
                <input type="text" class="form-control" asp-for="OidRefundNo" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/LianLianPay/WebQuickPay.cshtml
@model LianLianPayWebQuickPayViewModel
@{
    ViewData["Title"] = "WEB快捷支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="LianLianPay" asp-action="Index">连连支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="LianLianPay" asp-action="WebQuickPay" target="_blank">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoOrder"></label>
                <input type="text" class="form-control" asp-for="NoOrder" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="DtOrder"></label>
                <input type="text" class="form-control" asp-for="DtOrder" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="MoneyOrder"></label>
                <input type="text" class="form-control" asp-for="MoneyOrder" value="0.01" />
            </div>
            <div class="form-group">
                <label asp-for="NameGoods"></label>
                <input type="text" class="form-control" asp-for="NameGoods" value="WEB快捷支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="UserId"></label>
                <input type="text" class="form-control" asp-for="UserId" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/lianlianpay/receivemoney" />
            </div>
            <div class="form-group">
                <label asp-for="UrlReturn"></label>
                <input type="text" class="form-control" asp-for="UrlReturn" value="http://*/lianlianpay/quickpayreturn" />
            </div>
            <div class="form-group">
                <label asp-for="RiskItem"></label>
                <input type="text" class="form-control" asp-for="RiskItem" value='{"frms_ware_category":"1999","user_info_full_name":"你好"}' />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}