samples/WebApplicationSample/Models/JDPayViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationSample.Models
{
    public class JDPaySaveOrderViewModel
    {
        [Required]
        [Display(Name = "tradeNum")]
        public string TradeNum { get; set; }

        [Required]
        [Display(Name = "tradeName")]
        public string TradeName { get; set; }

        [Required]
        [Display(Name = "tradeTime")]
        public string TradeTime { get; set; }

        [Required]
        [Display(Name = "amount")]
        public string Amount { get; set; }

        [Required]
        [Display(Name = "orderType")]
        public string OrderType { get; set; }

        [Required]
        [Display(Name = "currency")]
        public string Currency { get; set; }

        [Required]
        [Display(Name = "callbackUrl")]
        public string CallbackUrl { get; set; }

        [Required]
        [Display(Name = "notifyUrl")]
        public string NotifyUrl { get; set; }

        [Display(Name = "userId")]
        public string UserId { get; set; }
    }

    public class JDPayUnifiedOrderViewModel
    {
        [Required]
        [Display(Name = "tradeNum")]
        public string TradeNum { get; set; }

        [Required]
        [Display(Name = "tradeName")]
        public string TradeName { get; set; }

        [Required]
        [Display(Name = "tradeTime")]
        public string TradeTime { get; set; }

        [Required]
        [Display(Name = "amount")]
        public string Amount { get; set; }

        [Required]
        [Display(Name = "orderType")]
        public string OrderType { get; set; }

        [Required]
        [Display(Name = "currency")]
        public string Currency { get; set; }

        [Required]
        [Display(Name = "notifyUrl")]
        public string NotifyUrl { get; set; }

        [Required]
        [Display(Name = "tradeType")]
        public string TradeType { get; set; }
    }

    public class JDPayQueryViewModel
    {
        [Required]
        [Display(Name = "tradeNum")]
        public string TradeNum { get; set; }

        [Display(Name = "oTradeNum")]
        public string OTradeNum { get; set; }

        [Required]
        [Display(Name = "tradeType")]
        public string TradeType { get; set; }
    }

    public class JDPayRefundViewModel
    {
        [Required]
        [Display(Name = "tradeNum")]
        public string TradeNum { get; set; }

        [Required]
        [Display(Name = "oTradeNum")]
        public string OTradeNum { get; set; }

        [Required]
        [Display(Name = "amount")]
        public string Amount { get; set; }

        [Required]
        [Display(Name = "currency")]
        public string Currency { get; set; }

        [Required]
        [Display(Name = "notifyUrl")]
        public string NotifyUrl { get; set; }
    }

    public class JDPayQueryRefundViewModel
    {
        [Required]
        [Display(Name = "tradeNum")]
        public string TradeNum { get; set; }

        [Display(Name = "oTradeNum")]
        public string OTradeNum { get; set; }

        [Required]
        [Display(Name = "tradeType")]
        public string TradeType { get; set; }
    }

    public class JDPayDefrayPayViewModel
    {
        [Required]
        [Display(Name = "request_datetime")]
        public string RequestDatetime { get; set; }

        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Display(Name = "biz_trade_no")]
        public string BizTradeNo { get; set; }

        [Display(Name = "out_trade_date")]
        public string OutTradeDate { get; set; }

        [Required]
        [Display(Name = "trade_amount")]
        public string TradeAmount { get; set; }

        [Required]
        [Display(Name = "trade_currency")]
        public string TradeCurrency { get; set; }

        [Display(Name = "seller_info")]
        public string SellerInfo { get; set; }

        [Required]
        [Display(Name = "trade_subject")]
        public string TradeSubject { get; set; }

        [Display(Name = "category_code")]
        public string CategoryCode { get; set; }

        [Required]
        [Display(Name = "pay_tool")]
        public string PayTool { get; set; }

        [Display(Name = "trade_source")]
        public string TradeSource { get; set; }

        [Display(Name = "payee_bank_code")]
        public string PayeeBankCode { get; set; }

        [Display(Name = "payee_bank_associated_code")]
        public string PayeeBankAssociatedCode { get; set; }

        [Display(Name = "payee_bank_fullname")]
        public string PayeeBankFullname { get; set; }

        [Display(Name = "payee_bank_country_code")]
        public string PayeeBankCountryCode { get; set; }

        [Display(Name = "payee_bank_province_code")]
        public string PayeeBankProvinceCode { get; set; }

        [Display(Name = "payee_bank_city_code")]
        public string PayeeBankCityCode { get; set; }

        [Display(Name = "payee_card_type")]
        public string PayeeCardType { get; set; }

        [Display(Name = "payee_account_type")]
        public string PayeeAccountType { get; set; }

        [Display(Name = "payee_account_no")]
        public string PayeeAccountNo { get; set; }

        [Display(Name = "payee_account_name")]
        public string PayeeAccountName { get; set; }

        [Display(Name = "payee_id_type")]
        public string PayeeIdType { get; set; }

        [Display(Name = "payee_id_no")]
        public string PayeeIdNo { get; set; }

        [Display(Name = "payee_mobile")]
        public string PayeeMobile { get; set; }

        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Display(Name = "return_params")]
        public string ReturnParams { get; set; }

        [Display(Name = "extend_params")]
        public string ExtendParams { get; set; }

        [Display(Name = "bank_card_info_type")]
        public string BankCardInfoType { get; set; }

        [Display(Name = "bank_card_id")]
        public string BankCardId { get; set; }
    }

    public class JDPayTradeQueryViewModel
    {
        [Required]
        [Display(Name = "request_datetime")]
        public string RequestDatetime { get; set; }

        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Display(Name = "trade_no")]
        public string TradeNo { get; set; }

        [Required]
        [Display(Name = "trade_type")]
        public string TradeType { get; set; }
    }
}

samples/WebApplicationSample/Controllers/JDPayController.cs
using System.Text;
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.JDPay;
using Essensoft.AspNetCore.Payment.JDPay.Notify;
using Essensoft.AspNetCore.Payment.JDPay.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class JDPayController : Controller
    {
        private readonly IJDPayClient _client;
        private readonly IJDPayNotifyClient _notifyClient;
        private readonly IOptions<JDPayOptions> _optionsAccessor;

        public JDPayController(IJDPayClient client, IJDPayNotifyClient notifyClient, IOptions<JDPayOptions> optionsAccessor)
        {
            _client = client;
            _notifyClient = notifyClient;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 京东支付指引页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// PC在线支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult SaveOrderPC()
        {
            return View();
        }

        /// <summary>
        /// PC在线支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SaveOrderPC(JDPaySaveOrderViewModel viewModel)
        {
            var request = new JDPaySaveOrderPCRequest
            {
                TradeNum = viewModel.TradeNum,
                TradeName = viewModel.TradeName,
                TradeTime = viewModel.TradeTime,
                Amount = viewModel.Amount,
                OrderType = viewModel.OrderType,
                Currency = viewModel.Currency,
                CallbackUrl = viewModel.CallbackUrl,
                NotifyUrl = viewModel.NotifyUrl,
                UserId = viewModel.UserId
            };

            var response = await _client.PageExecuteAsync(request, _optionsAccessor.Value);
            return Content(response.Body, "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// H5在线支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult SaveOrderH5()
        {
            return View();
        }

        /// <summary>
        /// H5在线支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SaveOrderH5(JDPaySaveOrderViewModel viewModel)
        {
            var request = new JDPaySaveOrderH5Request
            {
                TradeNum = viewModel.TradeNum,
                TradeName = viewModel.TradeName,
                TradeTime = viewModel.TradeTime,
                Amount = viewModel.Amount,
                OrderType = viewModel.OrderType,
                Currency = viewModel.Currency,
                CallbackUrl = viewModel.CallbackUrl,
                NotifyUrl = viewModel.NotifyUrl,
                UserId = viewModel.UserId
            };

            var response = await _client.PageExecuteAsync(request, _optionsAccessor.Value);
            return Content(response.Body, "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QrCodePay()
        {
            return View();
        }

        /// <summary>
        /// 扫码支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> QrCodePay(JDPayUnifiedOrderViewModel viewModel)
        {
            var request = new JDPayUnifiedOrderRequest
            {
                TradeNum = viewModel.TradeNum,
                TradeName = viewModel.TradeName,
                TradeTime = viewModel.TradeTime,
                Amount = viewModel.Amount,
                OrderType = viewModel.OrderType,
                Currency = viewModel.Currency,
                NotifyUrl = viewModel.NotifyUrl,
                TradeType = viewModel.TradeType
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["qrcode"] = response.QrCode;
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 交易查询接口
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Query()
        {
            return View();
        }

        /// <summary>
        /// 交易查询接口
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Query(JDPayQueryViewModel viewModel)
        {
            var request = new JDPayQueryRequest
            {
                TradeNum = viewModel.TradeNum,
                OTradeNum = viewModel.OTradeNum,
                TradeType = viewModel.TradeType
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 退款申请接口
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Refund()
        {
            return View();
        }

        /// <summary>
        /// 退款申请接口
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Refund(JDPayRefundViewModel viewModel)
        {
            var request = new JDPayRefundRequest
            {
                TradeNum = viewModel.TradeNum,
                OTradeNum = viewModel.OTradeNum,
                Amount = viewModel.Amount,
                Currency = viewModel.Currency,
                NotifyUrl = viewModel.NotifyUrl
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 退款查询接口
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QueryRefund()
        {
            return View();
        }

        /// <summary>
        /// 退款查询接口
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> QueryRefund(JDPayQueryRefundViewModel viewModel)
        {
            var request = new JDPayQueryRefundRequest
            {
                TradeNum = viewModel.TradeNum,
                OTradeNum = viewModel.OTradeNum,
                TradeType = viewModel.TradeType
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 代付交易请求
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DefrayPay()
        {
            return View();
        }

        /// <summary>
        /// 代付交易请求
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DefrayPay(JDPayDefrayPayViewModel viewModel)
        {
            var request = new JDPayDefrayPayRequest
            {
                RequestDatetime = viewModel.RequestDatetime,
                OutTradeNo = viewModel.OutTradeNo,
                BizTradeNo = viewModel.BizTradeNo,
                OutTradeDate = viewModel.OutTradeDate,
                TradeAmount = viewModel.TradeAmount,
                TradeCurrency = viewModel.TradeCurrency,
                SellerInfo = viewModel.SellerInfo,
                TradeSubject = viewModel.TradeSubject,
                CategoryCode = viewModel.CategoryCode,
                PayTool = viewModel.PayTool,
                TradeSource = viewModel.TradeSource,
                PayeeBankCode = viewModel.PayeeBankCode,
                PayeeBankAssociatedCode = viewModel.PayeeBankAssociatedCode,
                PayeeBankFullname = viewModel.PayeeBankFullname,
                PayeeBankCountryCode = viewModel.PayeeBankCountryCode,
                PayeeBankProvinceCode = viewModel.PayeeBankProvinceCode,
                PayeeBankCityCode = viewModel.PayeeBankCityCode,
                PayeeCardType = viewModel.PayeeCardType,
                PayeeAccountType = viewModel.PayeeAccountType,
                PayeeAccountNo = viewModel.PayeeAccountNo,
                PayeeAccountName = viewModel.PayeeAccountName,
                PayeeIdType = viewModel.PayeeIdType,
                PayeeIdNo = viewModel.PayeeIdNo,
                PayeeMobile = viewModel.PayeeMobile,
                NotifyUrl = viewModel.NotifyUrl,
                ReturnParams = viewModel.ReturnParams,
                ExtendParams = viewModel.ExtendParams,
                BankCardInfoType = viewModel.BankCardInfoType,
                BankCardId = viewModel.BankCardId
            };

            var response = await _client.ExecuteAsync(request, _optionsAccessor.Value);
            ViewData["response"] = response.Body;
            return View();
        }

        /// <summary>
        /// 代付交易查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult TradeQuery()
        {
            return View();
        }

        /// <summary>
        /// 代付交易查询
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> TradeQuery(JDPayTradeQueryViewModel viewModel)
        {

samples/WebApplicationSample/Views/JDPay/DefrayPay.cshtml
@model JDPayDefrayPayViewModel
@{
    ViewData["Title"] = "代付交易请求";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="JDPay" asp-action="Index">京东支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="JDPay" asp-action="DefrayPay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PayeeBankCode"></label>
                <input type="text" class="form-control" asp-for="PayeeBankCode" value="ABC" />
            </div>
            <div class="form-group">
                <label asp-for="ExtendParams"></label>
                <input type="text" class="form-control" asp-for="ExtendParams" value="{'ssss':'ssss'}" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeAccountType"></label>
                <input type="text" class="form-control" asp-for="PayeeAccountType" value="P" />
            </div>
            <div class="form-group">
                <label asp-for="ReturnParams"></label>
                <input type="text" class="form-control" asp-for="ReturnParams" value="1234ssddffgghhj" />
            </div>
            <div class="form-group">
                <label asp-for="TradeCurrency"></label>
                <input type="text" class="form-control" asp-for="TradeCurrency" value="CNY" />
            </div>
            <div class="form-group">
                <label asp-for="PayTool"></label>
                <input type="text" class="form-control" asp-for="PayTool" value="TRAN" />
            </div>
            <div class="form-group">
                <label asp-for="CategoryCode"></label>
                <input type="text" class="form-control" asp-for="CategoryCode" value="20jd222" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeAccountNo"></label>
                <input type="text" class="form-control" asp-for="PayeeAccountNo" value="6222600210011817312" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeAccountName"></label>
                <input type="text" class="form-control" asp-for="PayeeAccountName" value="张米克" />
            </div>
            <div class="form-group">
                <label asp-for="TradeSource"></label>
                <input type="text" class="form-control" asp-for="TradeSource" value="testetst" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/jdpay/defraypay" />
            </div>
            <div class="form-group">
                <label asp-for="BizTradeNo"></label>
                <input type="text" class="form-control" asp-for="BizTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="SellerInfo"></label>
                <input type="text" class="form-control" asp-for="SellerInfo" value="{'customer_code':'360080002191800017','customer_type':'CUSTOMER_NO'}" />
            </div>
            <div class="form-group">
                <label asp-for="OutTradeDate"></label>
                <input type="text" class="form-control" asp-for="OutTradeDate" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="TradeAmount"></label>
                <input type="text" class="form-control" asp-for="TradeAmount" value="1" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeBankFullname"></label>
                <input type="text" class="form-control" asp-for="PayeeBankFullname" value="农业银行" />
            </div>
            <div class="form-group">
                <label asp-for="RequestDatetime"></label>
                <input type="text" class="form-control" asp-for="RequestDatetime" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="TradeSubject"></label>
                <input type="text" class="form-control" asp-for="TradeSubject" value="test代付" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeCardType"></label>
                <input type="text" class="form-control" asp-for="PayeeCardType" value="DE" />
            </div>
            <div class="form-group">
                <label asp-for="PayeeMobile"></label>
                <input type="text" class="form-control" asp-for="PayeeMobile" value="1333333333" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/JDPay/Index.cshtml
@{
    ViewData["Title"] = "京东支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">首页</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">产品</th>
            <th scope="col">接口</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>在线支付接口PC版</td>
            <td><a href="https://payapi.jd.com/interface/saveOrder.html" target="_blank">https://wepay.jd.com/jdpay/saveOrder</a></td>
            <td><a asp-controller="JDPay" asp-action="SaveOrderPC">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>在线支付接口H5版</td>
            <td><a href="https://payapi.jd.com/interface/saveOrder.html" target="_blank">https://h5pay.jd.com/jdpay/saveOrder</a></td>
            <td><a asp-controller="JDPay" asp-action="SaveOrderH5">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>扫码支付-统一下单</td>
            <td><a href="https://payapi.jd.com/interface/uniorder.html" target="_blank">https://paygate.jd.com/service/uniorder</a></td>
            <td><a asp-controller="JDPay" asp-action="QrCodePay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>交易查询</td>
            <td><a href="https://payapi.jd.com/interface/query.html" target="_blank">https://paygate.jd.com/service/query</a></td>
            <td><a asp-controller="JDPay" asp-action="Query">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>退款申请</td>
            <td><a href="https://payapi.jd.com/interface/refund.html" target="_blank">https://paygate.jd.com/service/refund</a></td>
            <td><a asp-controller="JDPay" asp-action="Refund">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>退款查询</td>
            <td><a href="https://payapi.jd.com/interface/queryRefund.html" target="_blank">https://paygate.jd.com/service/queryRefund</a></td>
            <td><a asp-controller="JDPay" asp-action="QueryRefund">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <td>代付交易</td>
            <td>https://mapi.jdpay.com/npp10/defray_pay</td>
            <td><a asp-controller="JDPay" asp-action="DefrayPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">8</th>
            <td>代付交易查询</td>
            <td>https://mapi.jdpay.com/npp10/trade_query</td>
            <td><a asp-controller="JDPay" asp-action="TradeQuery">立即测试</a></td>
        </tr>
    </tbody>
</table>

samples/WebApplicationSample/Views/JDPay/QrCodePay.cshtml
@model JDPayUnifiedOrderViewModel
@{
    ViewData["Title"] = "扫码支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="JDPay" asp-action="Index">京东支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="JDPay" asp-action="QrCodePay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TradeNum"></label>
                <input type="text" class="form-control" asp-for="TradeNum" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="TradeName"></label>
                <input type="text" class="form-control" asp-for="TradeName" value="扫码支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="TradeTime"></label>
                <input type="text" class="form-control" asp-for="TradeTime" value="@DateTime.Now.ToString("yyyyMMddHHmmss")" />
            </div>
            <div class="form-group">
                <label asp-for="Amount"></label>
                <input type="text" class="form-control" asp-for="Amount" value="1" />
            </div>
            <div class="form-group">
                <label asp-for="OrderType"></label>
                <input type="text" class="form-control" asp-for="OrderType" value="1" />
            </div>
            <div class="form-group">
                <label asp-for="Currency"></label>
                <input type="text" class="form-control" asp-for="Currency" value="CNY" />
            </div>
            <div class="form-group">
                <label asp-for="TradeType"></label>
                <input type="text" class="form-control" asp-for="TradeType" value="QR" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/jdpay/async" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>QrCode:</label>
                @if (!string.IsNullOrEmpty(ViewData["qrcode"] as string))
                {
                <embed src="../Home/QrCode?size=168&data=@ViewData["qrcode"]" width="168" height="168" type="image/svg+xml" />
                }
            </div>
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/JDPay/Query.cshtml
@model JDPayQueryViewModel
@{
    ViewData["Title"] = "交易查询接口";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="JDPay" asp-action="Index">京东支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="JDPay" asp-action="Query">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TradeNum"></label>
                <input type="text" class="form-control" asp-for="TradeNum" />
            </div>
            <div class="form-group">
                <label asp-for="OTradeNum"></label>
                <input type="text" class="form-control" asp-for="OTradeNum" />
            </div>
            <div class="form-group">
                <label asp-for="TradeType"></label>
                <input type="text" class="form-control" asp-for="TradeType" value="0" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/JDPay/Return.cshtml
@{
    ViewData["Title"] = "在线支付-同步跳转";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="JDPay" asp-action="Index">京东支付</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        @ViewData["response"]
    </div>
</div>