samples/WebApplicationSample/Models/AlipayViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplicationSample.Models
{
    public class AlipayTradePreCreateViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "subject")]
        public string Subject { get; set; }

        [Display(Name = "body")]
        public string Body { get; set; }

        [Required]
        [Display(Name = "total_amount")]
        public string TotalAmount { get; set; }

        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class AlipayTradePayViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "subject")]
        public string Subject { get; set; }

        [Required]
        [Display(Name = "scene")]
        public string Scene { get; set; }

        [Required]
        [Display(Name = "auth_code")]
        public string AuthCode { get; set; }

        [Display(Name = "body")]
        public string Body { get; set; }

        [Required]
        [Display(Name = "total_amount")]
        public string TotalAmount { get; set; }
    }

    public class AlipayTradeAppPayViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "subject")]
        public string Subject { get; set; }

        [Display(Name = "product_code")]
        public string ProductCode { get; set; }

        [Display(Name = "body")]
        public string Body { get; set; }

        [Required]
        [Display(Name = "total_amount")]
        public string TotalAmount { get; set; }

        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }
    }

    public class AlipayTradePagePayViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "subject")]
        public string Subject { get; set; }

        [Required]
        [Display(Name = "product_code")]
        public string ProductCode { get; set; }

        [Display(Name = "body")]
        public string Body { get; set; }

        [Required]
        [Display(Name = "total_amount")]
        public string TotalAmount { get; set; }

        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Display(Name = "return_url")]
        public string ReturnUrl { get; set; }
    }

    public class AlipayTradeWapPayViewModel
    {
        [Required]
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Required]
        [Display(Name = "subject")]
        public string Subject { get; set; }

        [Required]
        [Display(Name = "product_code")]
        public string ProductCode { get; set; }

        [Display(Name = "body")]
        public string Body { get; set; }

        [Required]
        [Display(Name = "total_amount")]
        public string TotalAmount { get; set; }

        [Display(Name = "notify_url")]
        public string NotifyUrl { get; set; }

        [Display(Name = "return_url")]
        public string ReturnUrl { get; set; }
    }

    public class AlipayTradeQueryViewModel
    {
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Display(Name = "trade_no")]
        public string TradeNo { get; set; }
    }

    public class AlipayTradeRefundViewModel
    {
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Display(Name = "trade_no")]
        public string TradeNo { get; set; }

        [Display(Name = "refund_amount")]
        public string RefundAmount { get; set; }

        [Display(Name = "out_request_no")]
        public string OutRequestNo { get; set; }

        [Display(Name = "refund_reason")]
        public string RefundReason { get; set; }
    }

    public class AlipayTradeRefundQueryViewModel
    {
        [Display(Name = "out_trade_no")]
        public string OutTradeNo { get; set; }

        [Display(Name = "trade_no")]
        public string TradeNo { get; set; }

        [Display(Name = "out_request_no")]
        public string OutRequestNo { get; set; }
    }
    
    public class AlipayTransferViewModel
    {
        [Required]
        [Display(Name = "out_biz_no")]
        public string OutBizNo { get; set; }

        [Required]
        [Display(Name = "payee_account")]
        public string PayeeAccount { get; set; }

        [Required]
        [Display(Name = "payee_type")]
        public string PayeeType { get; set; }

        [Required]
        [Display(Name = "amount")]
        public string Amount { get; set; }

        [Display(Name = "remark")]
        public string Remark { get; set; }
    }

    public class AlipayTransQueryViewModel
    {
        [Display(Name = "out_biz_no")]
        public string OutBizNo { get; set; }

        [Display(Name = "order_id")]
        public string OrderId { get; set; }
    }

    public class AlipayBillDownloadurlQueryViewModel
    {
        [Required]
        [Display(Name = "bill_type")]
        public string BillType { get; set; }

        [Required]
        [Display(Name = "bill_date")]
        public string BillDate { get; set; }
    }
}

samples/WebApplicationSample/Controllers/AlipayController.cs
using System.Text;
using System.Threading.Tasks;
using Essensoft.AspNetCore.Payment.Alipay;
using Essensoft.AspNetCore.Payment.Alipay.Domain;
using Essensoft.AspNetCore.Payment.Alipay.Notify;
using Essensoft.AspNetCore.Payment.Alipay.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplicationSample.Models;

namespace WebApplicationSample.Controllers
{
    public class AlipayController : Controller
    {
        private readonly IAlipayClient _client;
        private readonly IAlipayNotifyClient _notifyClient;
        private readonly IOptions<AlipayOptions> _optionsAccessor;

        public AlipayController(IAlipayClient client, IAlipayNotifyClient notifyClient, IOptions<AlipayOptions> optionsAccessor)
        {
            _client = client;
            _notifyClient = notifyClient;
            _optionsAccessor = optionsAccessor;
        }

        /// <summary>
        /// 支付宝指引页
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 当面付-扫码支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult PreCreate()
        {
            return View();
        }

        /// <summary>
        /// 当面付-扫码支付
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PreCreate(AlipayTradePreCreateViewModel viewModel)
        {
            var model = new AlipayTradePrecreateModel
            {
                OutTradeNo = viewModel.OutTradeNo,
                Subject = viewModel.Subject,
                TotalAmount = viewModel.TotalAmount,
                Body = viewModel.Body
            };
            var req = new AlipayTradePrecreateRequest();
            req.SetBizModel(model);
            req.SetNotifyUrl(viewModel.NotifyUrl);

            var response = await _client.ExecuteAsync(req, _optionsAccessor.Value);
            ViewData["qrcode"] = response.QrCode;
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 当面付-二维码/条码/声波支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Pay()
        {
            return View();
        }

        /// <summary>
        /// 当面付-二维码/条码/声波支付
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Pay(AlipayTradePayViewModel viewModel)
        {
            var model = new AlipayTradePayModel
            {
                OutTradeNo = viewModel.OutTradeNo,
                Subject = viewModel.Subject,
                Scene = viewModel.Scene,
                AuthCode = viewModel.AuthCode,
                TotalAmount = viewModel.TotalAmount,
                Body = viewModel.Body
            };
            var req = new AlipayTradePayRequest();
            req.SetBizModel(model);

            var response = await _client.ExecuteAsync(req, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AppPay()
        {
            return View();
        }

        /// <summary>
        /// APP支付
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AppPay(AlipayTradeAppPayViewModel viewModel)
        {
            var model = new AlipayTradeAppPayModel
            {
                OutTradeNo = viewModel.OutTradeNo,
                Subject = viewModel.Subject,
                ProductCode = viewModel.ProductCode,
                TotalAmount = viewModel.TotalAmount,
                Body = viewModel.Body
            };
            var req = new AlipayTradeAppPayRequest();
            req.SetBizModel(model);
            req.SetNotifyUrl(viewModel.NotifyUrl);

            var response = await _client.SdkExecuteAsync(req, _optionsAccessor.Value);
            //将response.Body给 ios/android端 由其去调起支付宝APP(https://docs.open.alipay.com/204/105296/ https://docs.open.alipay.com/204/105295/)
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 电脑网站支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult PagePay()
        {
            return View();
        }

        /// <summary>
        /// 电脑网站支付
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> PagePay(AlipayTradePagePayViewModel viewModel)
        {
            var model = new AlipayTradePagePayModel
            {
                Body = viewModel.Body,
                Subject = viewModel.Subject,
                TotalAmount = viewModel.TotalAmount,
                OutTradeNo = viewModel.OutTradeNo,
                ProductCode = viewModel.ProductCode
            };
            var req = new AlipayTradePagePayRequest();
            req.SetBizModel(model);
            req.SetNotifyUrl(viewModel.NotifyUrl);
            req.SetReturnUrl(viewModel.ReturnUrl);

            var response = await _client.PageExecuteAsync(req, _optionsAccessor.Value);
            return Content(response.ResponseBody, "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// 手机网站支付
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult WapPay()
        {
            return View();
        }

        /// <summary>
        /// 手机网站支付
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> WapPay(AlipayTradeWapPayViewModel viewMode)
        {
            var model = new AlipayTradeWapPayModel
            {
                Body = viewMode.Body,
                Subject = viewMode.Subject,
                TotalAmount = viewMode.TotalAmount,
                OutTradeNo = viewMode.OutTradeNo,
                ProductCode = viewMode.ProductCode
            };
            var req = new AlipayTradeWapPayRequest();
            req.SetBizModel(model);
            req.SetNotifyUrl(viewMode.NotifyUrl);
            req.SetReturnUrl(viewMode.ReturnUrl);

            var response = await _client.PageExecuteAsync(req, _optionsAccessor.Value);
            return Content(response.ResponseBody, "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// 交易查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Query()
        {
            return View();
        }

        /// <summary>
        /// 交易查询
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Query(AlipayTradeQueryViewModel viewMode)
        {
            var model = new AlipayTradeQueryModel
            {
                OutTradeNo = viewMode.OutTradeNo,
                TradeNo = viewMode.TradeNo
            };

            var req = new AlipayTradeQueryRequest();
            req.SetBizModel(model);

            var response = await _client.ExecuteAsync(req, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 交易退款
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Refund()
        {
            return View();
        }

        /// <summary>
        /// 交易退款
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Refund(AlipayTradeRefundViewModel viewMode)
        {
            var model = new AlipayTradeRefundModel
            {
                OutTradeNo = viewMode.OutTradeNo,
                TradeNo = viewMode.TradeNo,
                RefundAmount = viewMode.RefundAmount,
                OutRequestNo = viewMode.OutRequestNo,
                RefundReason = viewMode.RefundReason
            };

            var req = new AlipayTradeRefundRequest();
            req.SetBizModel(model);

            var response = await _client.ExecuteAsync(req, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult RefundQuery()
        {
            return View();
        }

        /// <summary>
        /// 退款查询
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RefundQuery(AlipayTradeRefundQueryViewModel viewMode)
        {
            var model = new AlipayTradeFastpayRefundQueryModel
            {
                OutTradeNo = viewMode.OutTradeNo,
                TradeNo = viewMode.TradeNo,
                OutRequestNo = viewMode.OutRequestNo
            };

            var req = new AlipayTradeFastpayRefundQueryRequest();
            req.SetBizModel(model);

            var response = await _client.ExecuteAsync(req, _optionsAccessor.Value);
            ViewData["response"] = response.ResponseBody;
            return View();
        }

        /// <summary>
        /// 单笔转账到支付宝账户
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Transfer()
        {
            return View();
        }

        /// <summary>
        /// 单笔转账到支付宝账户
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Transfer(AlipayTransferViewModel viewMode)
        {
            var model = new AlipayFundTransToaccountTransferModel
            {

samples/WebApplicationSample/Views/Alipay/AppPay.cshtml
@model AlipayTradeAppPayViewModel
@{
    ViewData["Title"] = "APP支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Alipay" asp-action="AppPay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Subject"></label>
                <input type="text" class="form-control" asp-for="Subject" value="APP支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input type="text" class="form-control" asp-for="Body" value="APP支付描述信息" />
            </div>
            <div class="form-group">
                <label asp-for="ProductCode"></label>
                <input type="text" class="form-control" asp-for="ProductCode" />
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount"></label>
                <input type="text" class="form-control" asp-for="TotalAmount" value="0.01" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/alipay/apppay" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/Alipay/BillDownloadurlQuery.cshtml
@model AlipayBillDownloadurlQueryViewModel
@{
    ViewData["Title"] = "查询对账单下载地址";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Alipay" asp-action="BillDownloadurlQuery">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillDate"></label>
                <input type="text" class="form-control" asp-for="BillDate" />
            </div>
            <div class="form-group">
                <label asp-for="BillType"></label>
                <input type="text" class="form-control" asp-for="BillType" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/Alipay/Index.cshtml
@{
    ViewData["Title"] = "支付宝";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">首页</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">产品</th>
            <th scope="col">接口</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>当面付-扫码支付</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.precreate" target="_blank">alipay.trade.precreate</a></td>
            <td><a asp-controller="Alipay" asp-action="PreCreate">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>当面付-二维码/条码/声波支付</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.pay" target="_blank">alipay.trade.pay</a></td>
            <td><a asp-controller="Alipay" asp-action="Pay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>App支付</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.app.pay" target="_blank">alipay.trade.app.pay</a></td>
            <td><a asp-controller="Alipay" asp-action="AppPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>手机网站支付</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.wap.pay" target="_blank">alipay.trade.wap.pay</a></td>
            <td><a asp-controller="Alipay" asp-action="WapPay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>电脑网站支付</td>
            <td><a href="https://docs.open.alipay.com/270/alipay.trade.page.pay" target="_blank">alipay.trade.page.pay</a></td>
            <td><a asp-controller="Alipay" asp-action="PagePay">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>交易查询</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.query" target="_blank">alipay.trade.query</a></td>
            <td><a asp-controller="Alipay" asp-action="Query">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <td>交易退款</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.refund" target="_blank">alipay.trade.refund</a></td>
            <td><a asp-controller="Alipay" asp-action="Refund">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">8</th>
            <td>退款查询</td>
            <td><a href="https://docs.open.alipay.com/api_1/alipay.trade.fastpay.refund.query" target="_blank">alipay.trade.fastpay.refund.query</a></td>
            <td><a asp-controller="Alipay" asp-action="RefundQuery">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">9</th>
            <td>单笔转账到支付宝账户</td>
            <td><a href="https://docs.open.alipay.com/api_28/alipay.fund.trans.toaccount.transfer" target="_blank">alipay.fund.trans.toaccount.transfer</a></td>
            <td><a asp-controller="Alipay" asp-action="Transfer">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">10</th>
            <td>查询转账订单</td>
            <td><a href="https://docs.open.alipay.com/api_28/alipay.fund.trans.order.query" target="_blank">alipay.fund.trans.order.query</a></td>
            <td><a asp-controller="Alipay" asp-action="TransQuery">立即测试</a></td>
        </tr>
        <tr>
            <th scope="row">11</th>
            <td>查询对账单下载地址</td>
            <td><a href="https://docs.open.alipay.com/api_15/alipay.data.dataservice.bill.downloadurl.query" target="_blank">alipay.data.dataservice.bill.downloadurl.query</a></td>
            <td><a asp-controller="Alipay" asp-action="BillDownloadurlQuery">立即测试</a></td>
        </tr>
</table>

samples/WebApplicationSample/Views/Alipay/PagePay.cshtml
@model AlipayTradePagePayViewModel
@{
    ViewData["Title"] = "电脑网站支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Alipay" asp-action="PagePay" target="_blank">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Subject"></label>
                <input type="text" class="form-control" asp-for="Subject" value="电脑网站支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="ProductCode"></label>
                <input type="text" class="form-control" asp-for="ProductCode" value="FAST_INSTANT_TRADE_PAY" />
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input type="text" class="form-control" asp-for="Body" value="电脑网站支付描述信息" />
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount"></label>
                <input type="text" class="form-control" asp-for="TotalAmount" value="0.01" />
            </div>
            <div class="form-group">
                <label asp-for="ReturnUrl"></label>
                <input type="text" class="form-control" asp-for="ReturnUrl" value="http://*/alipay/pagepayreturn" />
            </div>
            <div class="form-group">
                <label asp-for="NotifyUrl"></label>
                <input type="text" class="form-control" asp-for="NotifyUrl" value="http://*/notify/alipay/pagepay" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/Alipay/PagePayReturn.cshtml
@{
    ViewData["Title"] = "电脑网站支付-同步跳转";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        @ViewData["response"]
    </div>
</div>

samples/WebApplicationSample/Views/Alipay/Pay.cshtml
@model AlipayTradePayViewModel
@{
    ViewData["Title"] = "当面付-二维码/条码/声波支付";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        <form asp-controller="Alipay" asp-action="Pay">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OutTradeNo"></label>
                <input type="text" class="form-control" asp-for="OutTradeNo" value="@DateTime.Now.ToString("yyyyMMddHHmmssfff")" />
            </div>
            <div class="form-group">
                <label asp-for="Subject"></label>
                <input type="text" class="form-control" asp-for="Subject" value="二维码/条码/声波支付测试" />
            </div>
            <div class="form-group">
                <label asp-for="Scene"></label>
                <input type="text" class="form-control" asp-for="Scene" value="bar_code" />
            </div>
            <div class="form-group">
                <label asp-for="AuthCode"></label>
                <input type="text" class="form-control" asp-for="AuthCode" />
            </div>
            <div class="form-group">
                <label asp-for="Body"></label>
                <input type="text" class="form-control" asp-for="Body" value="二维码/条码/声波支付描述信息" />
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount"></label>
                <input type="text" class="form-control" asp-for="TotalAmount" value="0.01" />
            </div>
            <button type="submit" class="btn btn-primary">提交请求</button>
        </form>
        <hr />
        <form class="form-horizontal">
            <div class="form-group">
                <label>Response:</label>
                <textarea class="form-control" rows="10">@ViewData["response"]</textarea>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

samples/WebApplicationSample/Views/Alipay/WapPayReturn.cshtml
@{
    ViewData["Title"] = "手机网站支付-同步跳转";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Alipay" asp-action="Index">支付宝</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
    </ol>
</nav>
<br />
<div class="card">
    <div class="card-body">
        @ViewData["response"]
    </div>
</div>